# Generated by Django 6.0.2 on 2026-03-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_flavor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flavor',
            constraint=models.UniqueConstraint(fields=('name', 'coffee'), name='unique_coffee_flavor'),
        ),
    ]
