# Generated by Django 6.0.2 on 2026-03-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_flavor_unique_coffee_flavor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flavor',
            name='unique_coffee_flavor',
        ),
        migrations.AddField(
            model_name='coffee',
            name='flavors',
            field=models.ManyToManyField(to='main_app.flavor'),
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='coffee',
        ),
    ]
